name: Demo Build Pipeline.

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  export-kicad:
    env:
      BaseFileName: "demo"
      Folder: "./pcb"
      SchematicFileExtension: "kicad_sch"
      PCBFileExtension: "kicad_pcb"
      OutputFolder: "./output"
      ConfigFilePath: ".kibot/build.kibot.yaml"
    runs-on: ubuntu-latest
    container: ghcr.io/inti-cmnb/kicad8_auto_full:dev
    steps:
    - name: Fetch repository
      uses: actions/checkout@v4
    
    - name: Prepare output directory
      run: |
        mkdir -p ${{ env.OutputFolder }}
        cp -r ${{ env.Folder }} ${{ env.OutputFolder }}/kicad
        cp ./LICENSE ${{ env.OutputFolder }}

    - name: Run KiBOT
      run: |
        kibot -c ${{ env.ConfigFilePath }} -d ${{ env.OutputFolder }} -b "${{ env.Folder }}/${{ env.BaseFileName }}.${{ env.PCBFileExtension }}" -s all -L ${{ env.OutputFolder }}/log board_top_filled

    - name: Archive artifacts
      uses: actions/upload-artifact@v4
      with:
        name: kicad-export
        path: ${{ env.OutputFolder }}
        retention-days: 1